# Java Maven CircleCI 2.0 configuration file

version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install dependencies for CircleCI (e.g. JARs from submodule rest-model)
      # but skips tests :-(
      - run: mvn install -Dskiptests
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests! and gen code coverage
      - run: mvn clean test

      - store_artifacts:
          path: target

      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
